// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0eobNKHDaaHvPWmt4gUrbvbKuFBarCCw',
    appId: '1:1002662749730:web:ea7cf36907f2272d1f4c7b',
    messagingSenderId: '1002662749730',
    projectId: 'dashboardgrievance',
    authDomain: 'dashboardgrievance.firebaseapp.com',
    storageBucket: 'dashboardgrievance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FnF65obQSl8_5vmLO04pYznRgELAQyI',
    appId: '1:1002662749730:android:ef7ab73826a6b3e11f4c7b',
    messagingSenderId: '1002662749730',
    projectId: 'dashboardgrievance',
    storageBucket: 'dashboardgrievance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrzvOlmQnw7inSyDiSHCAPtZFlcLFnW0',
    appId: '1:1002662749730:ios:ed55f2718d7f0a1d1f4c7b',
    messagingSenderId: '1002662749730',
    projectId: 'dashboardgrievance',
    storageBucket: 'dashboardgrievance.firebasestorage.app',
    iosBundleId: 'com.example.grievanceManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANrzvOlmQnw7inSyDiSHCAPtZFlcLFnW0',
    appId: '1:1002662749730:ios:ed55f2718d7f0a1d1f4c7b',
    messagingSenderId: '1002662749730',
    projectId: 'dashboardgrievance',
    storageBucket: 'dashboardgrievance.firebasestorage.app',
    iosBundleId: 'com.example.grievanceManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0eobNKHDaaHvPWmt4gUrbvbKuFBarCCw',
    appId: '1:1002662749730:web:884f74a00e101d411f4c7b',
    messagingSenderId: '1002662749730',
    projectId: 'dashboardgrievance',
    authDomain: 'dashboardgrievance.firebaseapp.com',
    storageBucket: 'dashboardgrievance.firebasestorage.app',
  );
}
